const SUPABASE_URL = 'https://qjfeurisdvhalxjgfmfu.supabase.co';
const SUPABASE_KEY = 'sb_publishable_mwnLEIXigyylVI44AkDO4w_WIM_xAPy';
const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

const FINMIND_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAyNi0wMS0yOCAxMToyOToyNSIsInVzZXJfaWQiOiJyaWNoYXJka3VvIiwiZW1haWwiOiJrdW8wOTM3NDcyMTk0QGdtYWlsLmNvbSIsImlwIjoiMjE4LjE3Mi4zMi4yNDIifQ.26zJgMi38O2JJyJioRLvp05qZrBp8XW5N4NvnQ8s6Y8';
